version: '3'
services:
  mongo:
    image: mongo:4.2.23-bionic
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: root
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
